<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Test Case is passed ]]>
    </line>
  </reporter-output>
  <suite started-at="2020-07-10T21:54:28 IST" name="Data Driven Framework" finished-at="2020-07-10T21:54:31 IST" duration-ms="3243">
    <groups>
    </groups>
    <test started-at="2020-07-10T21:54:28 IST" name="Bank Manager Login Test" finished-at="2020-07-10T21:54:31 IST" duration-ms="3193">
      <class name="com.iggroup.testcases.BankManagerLoginTest">
        <test-method signature="loginAsBankManager()[pri:0, instance:com.iggroup.testcases.BankManagerLoginTest@6356695f]" started-at="2020-07-10T21:54:28 IST" name="loginAsBankManager" finished-at="2020-07-10T21:54:31 IST" duration-ms="3144" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Test Case is passed ]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.iggroup.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test started-at="2020-07-10T21:54:31 IST" name="Add Customer Test" finished-at="2020-07-10T21:54:31 IST" duration-ms="7">
      <class name="com.iggroup.testcases.AddCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.iggroup.testcases.AddCustomerTest@564fabc8]" started-at="2020-07-10T21:54:23 IST" name="setUp" finished-at="2020-07-10T21:54:28 IST" duration-ms="5326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addCustomer()[pri:0, instance:com.iggroup.testcases.AddCustomerTest@564fabc8]" started-at="2020-07-10T21:54:31 IST" name="addCustomer" finished-at="2020-07-10T21:54:31 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing the test case]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing the test case
at org.testng.Assert.fail(Assert.java:97)
at com.iggroup.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.iggroup.testcases.AddCustomerTest@564fabc8]" started-at="2020-07-10T21:54:31 IST" name="tearDown" finished-at="2020-07-10T21:54:32 IST" duration-ms="799" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.iggroup.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Framework -->
</testng-results>
